### ISSUE TITLE
How to execute org-thtml

### ISSUE THREAD

**Issue by hs0ucy** [juanjosegarciaripoll/org-thtml#1]
Hi,

Your app it's exactly what i was looking for ... But i don't understand how to build the site within Emacs?

Thanks for your help!

Ciao

**Comment by juanjosegarciaripoll** [comment]
There is a step by step example of a personal site. It would help if you
would provide a bit more information about what you do not understand.

Hugo Soucy <notifications@github.com> writes:
> Hi,
>
> Your app it's exactly what i was looking for ... But i don't
> understand how to build the site within Emacs?
>
> Thanks for your help!
>
> Ciao

-- 
Juan José García Ripoll

Quantum Information and Foundations Group
Institute of Fundamental Physics IFF-CSIC
Calle Serrano 113b, Madrid 28006 Spain
http://quinfog.hbar.es - http://juanjose.garcia.ripoll

**Comment by balaramadurai** [comment]
@hs0ucy , try this...

  `git clone https://github.com/juanjosegarciaripoll/org-thtml`
  `cd org-thtml`
   `make examples`

from the command line. 

You can then change parameters from the example site and create your own.

Hope this helps
Bala

**Comment by juanjosegarciaripoll** [comment]
org-thtml is not "executed" by itself. Instead, it is one backend for org-export which gets invoked when you use org-publish.

However, since HTML sites are relatively complex projects, they require quite a lot of boilerplate to configure how the templates should be set up, where to find your posts, etc.

Please have a look at the Emacs Lisp file [make.el](https://github.com/juanjosegarciaripoll/org-thtml/blob/master/personal-site/make.el), to see how this is done. This file configures a personal site up from files stored in the personal-site directory. You can use it and the directories inside to build a more complex configuration.

To create the site, load `org-thml.el`, then open `make.el` and run it to perform all the configuration steps and export the HTML files. Note that the actual work is performed by the calls to `org-publish` and `templated-html-create-sitemap-xml` at the end of the file.
